#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Nov 01 22:35:41 EDT 2024
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 1d7e24dda4c14e1b8362bd5d9702b6ac --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot t_sixtyfourBitSignedDivider_behav xil_defaultlib.t_sixtyfourBitSignedDivider xil_defaultlib.glbl -log elaborate.log"
xelab -wto 1d7e24dda4c14e1b8362bd5d9702b6ac --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot t_sixtyfourBitSignedDivider_behav xil_defaultlib.t_sixtyfourBitSignedDivider xil_defaultlib.glbl -log elaborate.log

